---
kind: pipeline
name: isudo.ru CI/CD

steps:
  - name: Setup config
    pull: always
    image: plugins/ansible:1
    settings:
      playbook: playbook.yml
      inventory: not-exists.ini
      vault_password:
        from_secret: VAULT

  - name: Tests
    pull: always
    image: python:3.8-slim
    commands:
      - pip3 install poetry
      - poetry install
      - poetry run pytest

  - name: Deploy
    pull: always
    image: python:3.8-slim
    commands:
      - poetry run python cli.py deploy
    when:
      branch:
        - master
