---
kind: pipeline
name: isudo.ru CI/CD

steps:
  - name: Setup config
    pull: always
    image: plugins/ansible:1
    settings:
      playbook: playbook.yml
      inventory: not-exists.ini
      vault_password:
        from_secret: VAULT

  - name: Install
    pull: always
    image: python:3.8-slim
    environment:
      XDG_CACHE_HOME: .cache
      POETRY_VIRTUALENVS_PATH: .cache
    commands:
      - pip3 install poetry
      - poetry install

  - name: Test
    pull: always
    image: python:3.8-slim
    environment:
      XDG_CACHE_HOME: .cache
      POETRY_VIRTUALENVS_PATH: .cache
    commands:
      - pip3 install poetry
      - poetry run pytest

  - name: Build
    pull: always
    image: python:3.8-slim
    environment:
      XDG_CACHE_HOME: .cache
      POETRY_VIRTUALENVS_PATH: .cache
    commands:
      - pip3 install poetry
      - poetry run python cli.py build

  - name: Deploy
    pull: always
    image: python:3.8-slim
    environment:
      XDG_CACHE_HOME: .cache
      POETRY_VIRTUALENVS_PATH: .cache
    commands:
      - pip3 install poetry
      - poetry run python cli.py deploy
    when:
      branch:
        - master
